### ISSUE TITLE
[Bug] RuntimeError: Detected recursive loop for /usr/local/airflow/dags/dbt/dbt_venv/lib

### ISSUE THREAD

**Issue by oliverrmaa** [astronomer/astronomer-cosmos#1076] opened 2024-07-02 06:36 UTC
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.4.3

### dbt-core version

1.7.17

### Versions of dbt adapters

dbt-bigquery==1.7.4
dbt-core==1.7.17
dbt-extractor==0.5.1
dbt-semantic-interfaces==0.4.4

### LoadMode

DBT_LS

### ExecutionMode

LOCAL

### InvocationMode

SUBPROCESS

### airflow version

apache-airflow==2.9.2+astro.1

### Operating System

Debian GNU/Linux 11 (bullseye)

### Deployment

Astronomer

### Deployment details

We have a main production deployment in Astro Cloud which we consider as production. We also do local development via `astro dev start`. We have continuous deployment set up through CircleCI which deploys merged PRs to our master branch to our production deployment via `astro deploy --dags`. For authentication to our data warehouse (Google BigQuery) in production, we use `GoogleCloudServiceAccountDictProfileMapping` and for local we use `ProfileConfig` where our dbt profiles.yml has a hardcoded path to a service account JSON file which is at the same path for each developer.

### What happened?

We noticed that we are having a RuntimeError constantly (I believe every second according to our Astro production deployment logs): `Detected recursive loop when walking DAG directory /usr/local/airflow/dags: /usr/local/airflow/dags/dbt/dbt_venv/lib has appeared more than once.`

We aren't sure whether this error is going to cause parts of our setup to work sub optimally or connected to any other issues we are seeing in our production environment, i.e. like in https://github.com/astronomer/astronomer-cosmos/issues/1075, or if it will cause further issues in the future. 

### Relevant log output

```shell
06/25/24 15:19:42 PM	[2024-06-25T22:19:42.726+0000] {manager.py:737} INFO - Searching for files in /usr/local/airflow/dags Process ForkProcess-22795: Traceback (most recent call last): File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.11/site-packages/airflow/dag_processing/manager.py", line 241, in _run_processor_manager processor_manager.start() File "/usr/local/lib/python3.11/site-packages/airflow/dag_processing/manager.py", line 476, in start return self._run_parsing_loop() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/airflow/dag_processing/manager.py", line 549, in _run_parsing_loop self._refresh_dag_dir() File "/usr/local/lib/python3.11/site-packages/airflow/dag_processing/manager.py", line 738, in _refresh_dag_dir self._file_paths = list_py_file_paths(self._dag_directory) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/airflow/utils/file.py", line 298, in list_py_file_paths file_paths.extend(find_dag_file_paths(directory, safe_mode)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/airflow/utils/file.py", line 311, in find_dag_file_paths for file_path in find_path_from_directory(directory, ".airflowignore"): 

File "/usr/local/lib/python3.11/site-packages/airflow/utils/file.py", line 241, in _find_path_from_directory raise RuntimeError( RuntimeError: Detected recursive loop when walking DAG directory /usr/local/airflow/dags: /usr/local/airflow/dags/dbt/dbt_venv/lib has appeared more than once.
```

### How to reproduce

I believe having the same set up should cause this bug to occur, note however, we have 1000+ dbt models so a project of that size may be needed to test. 

Here are some relevant snippets for where our dbt_venv will live:

(1) Here is the relevant parts of our dockerfile: 

```
FROM quay.io/astronomer/astro-runtime:11.5.0

# install dbt into a virtual environment
ARG DBT_BIGQUERY_VERSION=1.7.4
RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
    pip install --no-cache-dir dbt-bigquery==$DBT_BIGQUERY_VERSION && deactivate
```

(2) Here is our ExecutionConfig

```
ExecutionConfig(
            execution_mode=ExecutionMode.LOCAL,
            dbt_executable_path=f"{os.environ['AIRFLOW_HOME']}/dbt_venv/bin/dbt",
        )
```

### Anything else :)?

Here is a screenshot of our production deployment logs in Astro UI where we found the bug, as you can see the issue is continuously happening: 

<img width="1570" alt="image" src="https://github.com/astronomer/astronomer-cosmos/assets/35436396/f3c19505-b65c-4009-a105-886ba8960233">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Contact Details

oma@forhims.com

**Comment by tatiana** [comment] 2024-07-17 08:44
Hi @oliverrmaa , thanks for the detailed description, this is very helpful!

Are you storing the dbt project files in  `/usr/local/airflow/dags/dbt/`?

Is `/usr/local/airflow/dags/dbt/dbt_venv/` a Python virtualenv containing the `dbt` installation?

Would it be possible to not have `dbt_venv` inside the dbt or Airflow DAGs folder? This should solve the issue.

**Comment by tatiana** [comment] 2024-07-24 00:32
@oliverrmaa  the root cause is that the Airflow DAGs folder contains a `dbt_venv` Python virtualenv folder that contains recursive loops. When this happens, the Airflow scheduler cannot parse the DAGs and cannot orchestrate workflows - it breaks.
 
Although Cosmos is not introducing this issue, we spiked on the implementation of two functions and a command line that could help clean up the DAGs directory during the deployment, which we shared today: #1115

We made this change available in an Alpha release: https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.6.0a3. You could try it out installing Cosmos using:

```
pip install astronomer-cosmos==v1.6.0a3
```
 
Alec mentioned that it was unclear how this folder was being created since it was not part of the Github repo. Therefore, this tooling would be less useful. For this reason, I'll close this PR without merging it with the main. Currently, these features will not be part of a stable Cosmos release. We can reopen this in the future if you or other community members find value on these methods.
 
Today, we also discussed that currently, your team has a few different ways of deploying to Astro, including:
a) From the CI/CD
b) Some developers use Astro CLI from their local machines
 
During the call, we reviewed (a) your Astro `Dockerfile` and confirmed that it is not creating the `dbt_venv` directory inside the DAGs directory.
 
Therefore, you're facing the problem because of deployments derived from local developers' computers (b). As we discussed, the ideal scenario would be for the virtualenv not to be created inside the dbt folder.
 
During the call, Alec mentioned he had been advised that files in the `.gitignore` were not deployed as part of the Astro deployment. I confirmed with the Astro CLI team today, and I'm afraid this information is inaccurate.
 
As of Astro CLI 1.27.1:
i) The Astro CLI does not use `.gitignore` in any way
ii) When performing image-based deployments, the Astro CLI takes into account `.dockerignore`
iii) When performing dag-based deployments (--dags), the Astro CLI does not use `.dockerignore`
 
There is a solution to avoid the problem from happening again - as long as the path of the `dbt_venv` is always in the exact location in the DAGs folder:
 
* Introduce a `.airflowignore` file inside your dags folder. It should contain the paths to all possible relative paths of the `dbt_venv` directory inside the DAGs folder. Example:
 
```
dbt_venv
dbt/dbt_venv
``` 

By doing this, Airflow should ignore these paths containing recursive loops and be able to parse DAGs, as explained in the docs:
 
* https://www.astronomer.io/docs/astro/cli/airflowignore
* https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#airflowignore
 
However, suppose developers create Python virtual environments with recursive loops in different paths in the DAGs folder. In that case, the issue will happen again: DAGs will not run on schedule. For this reason, it is essential to review and align with the team on the current deployment processes from local dev machines.

Future actions that are outside of the scope of Cosmos could be:
* To change Astro CLI to check if the `/dags` folder has recursive loops before any deployment - and erroring at the client-side: https://github.com/astronomer/astro-cli/issues/1682
* To change Airflow for it to stop raising a `RuntimeError` when it finds a recursive loop: https://github.com/apache/airflow/issues/40980

**Closed by tatiana** 2024-07-24 00:32 UTC
Labels: bug, customer request, profile:bigquery, execution:local, area:parsing, triage-needed
