### ISSUE TITLE
DBT

### ISSUE THREAD

**Issue by AkashSonu14** [astronomer/astronomer-cosmos#1421] opened 2024-12-23 04:58 UTC
Hi,
I want code for batch job executing and its triggers when the previous job is fails, in the integration of dbt cosmos and airflow

**Comment by pankajastro** [comment] 2024-12-23 14:30
Hey @AkashSonu14. Could you please confirm if this request in not a duplicate of https://github.com/astronomer/astronomer-cosmos/issues/1419

**Comment by AkashSonu14** [comment] 2024-12-24 10:55
@pankajastro I can't understand what you are saying

**Comment by pankajkoti** [comment] 2024-12-26 07:16
hi @AkashSonu14 could you please edit and update an appropriate title for this issue. Just having the title as "DBT" gives less idea on what the issue could be when the community looks at it. Please take a look at open issues https://github.com/astronomer/astronomer-cosmos/issues to see how the community reports issues wrt to Title and description.

**Comment by AkashSonu14** [comment] 2024-12-26 08:00
Issue solved

**Closed** 2024-12-26 09:06 UTC
Labels: area:execution
