### ISSUE TITLE
Outlets

### ISSUE THREAD

**Issue by ykuc** [astronomer/astronomer-cosmos#652] opened 2023-11-06 17:08 UTC
Outlets is empty when i use DbtRunLocalOperator. Isn’t it work or i need enable it?
![image](https://github.com/astronomer/astronomer-cosmos/assets/140019825/572d39c2-2256-4f10-b3a1-c0e2e8d3a8c8)

**Comment by ykuc** [comment] 2023-11-06 17:09
https://apache-airflow.slack.com/archives/C059CC42E9W/p1699032606516239

**Comment by jlaneve** [comment] 2023-11-06 20:42
This may be related to https://github.com/astronomer/astronomer-cosmos/issues/522 - I know we've had some difficulties with Datasets consistently appearing in the Airflow UI. @ykuc can you confirm your Airflow + Cosmos versions?

**Comment by ykuc** [comment] 2023-11-06 22:04
Airflow 2.7.2 and astronomer-cosmos 1.2.1

**Comment by tatiana** [comment] 2023-11-06 22:34
As pointed by @jlaneve  is a duplicate of #522 - so I'm closing it. Please, @ykuc , follow up on the other issue.

**Closed by tatiana** 2023-11-06 22:34 UTC
Labels: duplicate
