### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by martijnroo** [astronomer/astronomer-cosmos#1365] opened 2024-12-05 10:45 UTC
### Astronomer Cosmos Version

1.7.1

### dbt-core version

1.7.18

### Versions of dbt adapters

dbt-redshift==1.7.7

### LoadMode

AUTOMATIC

### ExecutionMode

LOCAL

### InvocationMode

None

### airflow version

2.7.3

### Operating System

MacOS

### Deployment

Astronomer

### What happened?

I have a dbt test that looks like this:
```sql
SELECT d_item.item_code,
       d_item.item_inventory_flag AS item_inventory_flag_in_analytical,
       flag.inventory_flag_value AS item_inventory_flag_in_source
FROM {{ ref('analytical_d_item') }}
INNER JOIN {{ ref('inventory_flag_sap') }} AS flag
    ON d_item.item_code = flag.item_code
WHERE d_item.item_inventory_flag <> flag.inventory_flag_value
```

Cosmos runs this test after the analytical_d_item model as well as after the inventory_flag_sap model, so the test is run two times. Because of this, the test runs before both models have run and therefore it always fails. The test should run after both models it depends on have run.

### Relevant log output

```shell

```

### How to reproduce

Create three files:
a.sql
```sql
SELECT 1 AS id
```
b.sql
```sql
SELECT id FROM {{ ref('a') }}
```
assert_c.sql
```sql
SELECT a.id, b.id
FROM {{ ref('a') }}
LEFT JOIN {{ ref('b') }} USING (id)
WHERE a.id != b.id
```

Since b depends on a, it will be run _after_ a's tests have run. assert_c is run directly after a, even though it depends on b as well. Cosmos ignores this. assert_c will fail, because table b doesn't exist yet.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by tatiana** [comment] 2024-12-05 16:00
Hi @martijnroo , thank you very much for reporting this issue!
It seems a duplicate of #978.
I'll tentatively add the original ticket to the Cosmos 1.8 milestone, and we'll address it in our next sprint.

**Closed** 2024-12-30 13:59 UTC
Labels: bug, duplicate, customer request, execution:local, dbt:test
